apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-quotes
  template:
    metadata:
      labels:
        app: office-quotes
    spec:
      containers:
        - name: postgres
          image: postgres:12.12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: office-quotes
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: office-quotes