apiVersion: v1
kind: PersistentVolume
metadata:
  name: office-quotes
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/office-quotes