apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-quotes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-quotes-api
  template:
    metadata:
      labels:
        app: office-quotes-api
    spec:
      containers:
        - name: app
          image: codingpierogi/office-quotes-api
          imagePullPolicy: "Always"
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: office-quotes-data
                  key: POSTGRES_USER
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: office-quotes-data
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgresql://$(USERNAME):$(SECRET)@office-quotes-data:5432/app?schema=officequotes
          ports:
            - containerPort: 4000
